
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/jyotirlinga_db?schema=public
      - NODE_ENV=production
      - NEXT_DIST_DIR=.next
      - NEXT_OUTPUT_MODE=standalone
    restart: always
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jyotirlinga_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  node_modules:
  postgres_data:
